# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genetico.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'genetico.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egenetico.proto\x12\x08genetico\"<\n\tIndividuo\x12\r\n\x05genes\x18\x01 \x03(\t\x12\x0f\n\x07\x61ptidao\x18\x02 \x01(\x02\x12\x0f\n\x07geracao\x18\x03 \x01(\x05\"n\n\x10MensagemMigracao\x12\'\n\nindividuos\x18\x01 \x03(\x0b\x32\x13.genetico.Individuo\x12\x12\n\nlamport_ts\x18\x02 \x01(\x03\x12\x0e\n\x06origem\x18\x03 \x01(\t\x12\r\n\x05\x63iclo\x18\x04 \x01(\x05\"U\n\x16MensagemRedistribuicao\x12\'\n\nindividuos\x18\x01 \x03(\x0b\x32\x13.genetico.Individuo\x12\x12\n\nlamport_ts\x18\x02 \x01(\x03\"$\n\x0fMensagemEleicao\x12\x11\n\tid_origem\x18\x01 \x01(\x05\"3\n\rMensagemLider\x12\x10\n\x08id_lider\x18\x01 \x01(\x05\x12\x10\n\x08\x65ndereco\x18\x02 \x01(\t\"+\n\x0b\x43onfirmacao\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"p\n\x06Status\x12\r\n\x05no_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63iclo_atual\x18\x02 \x01(\x05\x12\x15\n\rgeracao_atual\x18\x03 \x01(\x05\x12\x16\n\x0emelhor_aptidao\x18\x04 \x01(\x02\x12\x13\n\x0bmelhor_rota\x18\x05 \x01(\t\"\x07\n\x05Vazio2\xd9\x02\n\x0fGeneticoService\x12\x43\n\x0e\x45nviarMelhores\x12\x1a.genetico.MensagemMigracao\x1a\x15.genetico.Confirmacao\x12K\n\x10ReceberMigrantes\x12 .genetico.MensagemRedistribuicao\x1a\x15.genetico.Confirmacao\x12\x42\n\x0eReceberEleicao\x12\x19.genetico.MensagemEleicao\x1a\x15.genetico.Confirmacao\x12>\n\x0cReceberLider\x12\x17.genetico.MensagemLider\x1a\x15.genetico.Confirmacao\x12\x30\n\x0bObterStatus\x12\x0f.genetico.Vazio\x1a\x10.genetico.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genetico_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDIVIDUO']._serialized_start=28
  _globals['_INDIVIDUO']._serialized_end=88
  _globals['_MENSAGEMMIGRACAO']._serialized_start=90
  _globals['_MENSAGEMMIGRACAO']._serialized_end=200
  _globals['_MENSAGEMREDISTRIBUICAO']._serialized_start=202
  _globals['_MENSAGEMREDISTRIBUICAO']._serialized_end=287
  _globals['_MENSAGEMELEICAO']._serialized_start=289
  _globals['_MENSAGEMELEICAO']._serialized_end=325
  _globals['_MENSAGEMLIDER']._serialized_start=327
  _globals['_MENSAGEMLIDER']._serialized_end=378
  _globals['_CONFIRMACAO']._serialized_start=380
  _globals['_CONFIRMACAO']._serialized_end=423
  _globals['_STATUS']._serialized_start=425
  _globals['_STATUS']._serialized_end=537
  _globals['_VAZIO']._serialized_start=539
  _globals['_VAZIO']._serialized_end=546
  _globals['_GENETICOSERVICE']._serialized_start=549
  _globals['_GENETICOSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
