# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import genetico_pb2 as genetico__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in genetico_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneticoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMelhores = channel.unary_unary(
                '/genetico.GeneticoService/EnviarMelhores',
                request_serializer=genetico__pb2.MensagemMigracao.SerializeToString,
                response_deserializer=genetico__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ReceberMigrantes = channel.unary_unary(
                '/genetico.GeneticoService/ReceberMigrantes',
                request_serializer=genetico__pb2.MensagemRedistribuicao.SerializeToString,
                response_deserializer=genetico__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ReceberEleicao = channel.unary_unary(
                '/genetico.GeneticoService/ReceberEleicao',
                request_serializer=genetico__pb2.MensagemEleicao.SerializeToString,
                response_deserializer=genetico__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ReceberLider = channel.unary_unary(
                '/genetico.GeneticoService/ReceberLider',
                request_serializer=genetico__pb2.MensagemLider.SerializeToString,
                response_deserializer=genetico__pb2.Confirmacao.FromString,
                _registered_method=True)
        self.ObterStatus = channel.unary_unary(
                '/genetico.GeneticoService/ObterStatus',
                request_serializer=genetico__pb2.Vazio.SerializeToString,
                response_deserializer=genetico__pb2.Status.FromString,
                _registered_method=True)


class GeneticoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnviarMelhores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceberMigrantes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceberEleicao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceberLider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneticoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMelhores': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMelhores,
                    request_deserializer=genetico__pb2.MensagemMigracao.FromString,
                    response_serializer=genetico__pb2.Confirmacao.SerializeToString,
            ),
            'ReceberMigrantes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceberMigrantes,
                    request_deserializer=genetico__pb2.MensagemRedistribuicao.FromString,
                    response_serializer=genetico__pb2.Confirmacao.SerializeToString,
            ),
            'ReceberEleicao': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceberEleicao,
                    request_deserializer=genetico__pb2.MensagemEleicao.FromString,
                    response_serializer=genetico__pb2.Confirmacao.SerializeToString,
            ),
            'ReceberLider': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceberLider,
                    request_deserializer=genetico__pb2.MensagemLider.FromString,
                    response_serializer=genetico__pb2.Confirmacao.SerializeToString,
            ),
            'ObterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterStatus,
                    request_deserializer=genetico__pb2.Vazio.FromString,
                    response_serializer=genetico__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genetico.GeneticoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genetico.GeneticoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneticoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarMelhores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genetico.GeneticoService/EnviarMelhores',
            genetico__pb2.MensagemMigracao.SerializeToString,
            genetico__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceberMigrantes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genetico.GeneticoService/ReceberMigrantes',
            genetico__pb2.MensagemRedistribuicao.SerializeToString,
            genetico__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceberEleicao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genetico.GeneticoService/ReceberEleicao',
            genetico__pb2.MensagemEleicao.SerializeToString,
            genetico__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceberLider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genetico.GeneticoService/ReceberLider',
            genetico__pb2.MensagemLider.SerializeToString,
            genetico__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genetico.GeneticoService/ObterStatus',
            genetico__pb2.Vazio.SerializeToString,
            genetico__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
